import { REGISTRY_SQUID_URLS, REGISTRY_SUBGRAPH_URLS } from 'common-util/indexers';
import { SUB_HEADER_LG_CLASS, TEXT_MEDIUM_CLASS } from 'common-util/classes';
import {
  OMENSTRAT_AGENT_CLASSIFICATION,
  POLYSTRAT_AGENT_CLASSIFICATION,
} from 'common-util/constants';
import {
  agentTxCountsQuery,
  registryGlobalsQuery,
  registryGlobalsSquidQuery,
} from 'common-util/graphql/queries';
import SectionWrapper from 'components/Layout/SectionWrapper';
import { IndexerLinks } from './IndexerLinks';
import { SubgraphLink } from './SubgraphLink';
import { CodeSnippet } from './CodeSnippet';

export const TransactionsInfo = () => {
  return (
    <>
      <SectionWrapper id="transactions">
        <h2 className={SUB_HEADER_LG_CLASS}>Transactions</h2>

        <div className="space-y-6 mt-4">
          <p>
            Tracks the total number of transactions executed by all agents across all supported
            networks. This metric provides insight into the overall activity level and transaction
            volume generated by the autonomous agent ecosystem.
          </p>

          <p>The following query is used to compute total daily transactions:</p>

          <h3 className={`${TEXT_MEDIUM_CLASS} font-bold`}>Registry Globals query</h3>

          <p className="text-purple-600">
            Subgraph links: <IndexerLinks urls={REGISTRY_SUBGRAPH_URLS} />
          </p>
          <CodeSnippet>{registryGlobalsQuery}</CodeSnippet>
          <p className="text-purple-600">
            Squid links (OpenReader dialect): <IndexerLinks urls={REGISTRY_SQUID_URLS} />
          </p>
          <CodeSnippet>{registryGlobalsSquidQuery}</CodeSnippet>
        </div>
      </SectionWrapper>
      <SectionWrapper id="omenstrat-predict-transactions-by-type">
        <h2 className={SUB_HEADER_LG_CLASS}>Omenstrat: Transactions by Agent Type</h2>

        <div className="space-y-6 mt-4">
          <p>
            Breaks down total Predict transactions by agent category using agent-level counters.
            Categories mirror the UI: Traders, Mechs (Prediction Brokers), and Market
            Creators/Closers.
          </p>

          <h3 className={`${TEXT_MEDIUM_CLASS} font-bold`}>Classification used</h3>
          <div className="space-y-1">
            <p>
              <strong>Market maker</strong> agent IDs:{' '}
              {OMENSTRAT_AGENT_CLASSIFICATION.market_maker.join(', ')}
            </p>
            <p>
              <strong>Valory trader</strong> agent IDs:{' '}
              {OMENSTRAT_AGENT_CLASSIFICATION.valory_trader.join(', ')}
            </p>
            <p>
              <strong>Mech</strong> agent IDs: {OMENSTRAT_AGENT_CLASSIFICATION.mech.join(', ')}
            </p>
            {/* Other trader category intentionally excluded */}
          </div>

          <p>The following query is used to fetch per-agent tx counts:</p>

          <h3 className={`${TEXT_MEDIUM_CLASS} font-bold`}>Agent Performances query</h3>

          <p className="text-purple-600">
            Subgraph link:{' '}
            <SubgraphLink
              apiUrl={process.env.NEXT_PUBLIC_GNOSIS_REGISTRY_SUBGRAPH_URL}
              className="mr-2"
            >
              Gnosis
            </SubgraphLink>
          </p>
          <CodeSnippet>{agentTxCountsQuery}</CodeSnippet>
        </div>
      </SectionWrapper>
      <SectionWrapper id="polystrat-predict-transactions-by-type">
        <h2 className={SUB_HEADER_LG_CLASS}>Polystrat: Transactions by Agent Type</h2>

        <div className="space-y-6 mt-4">
          <p>
            Breaks down total Polystrat (Polymarket) transactions by agent category using
            agent-level counters. Categories mirror the UI: Traders and Mechs (Prediction Brokers).
          </p>

          <h3 className={`${TEXT_MEDIUM_CLASS} font-bold`}>Classification used</h3>
          <div className="space-y-1">
            <p>
              <strong>Valory trader</strong> agent IDs:{' '}
              {POLYSTRAT_AGENT_CLASSIFICATION.valory_trader.join(', ')}
            </p>
            <p>
              <strong>Mech</strong> agent IDs: {POLYSTRAT_AGENT_CLASSIFICATION.mech.join(', ')}
            </p>
          </div>

          <p>The following query is used to fetch per-agent tx counts:</p>

          <h3 className={`${TEXT_MEDIUM_CLASS} font-bold`}>Agent Performances query</h3>

          <p className="text-purple-600">
            Subgraph link:{' '}
            <SubgraphLink
              apiUrl={process.env.NEXT_PUBLIC_POLYGON_REGISTRY_SUBGRAPH_URL}
              className="mr-2"
            >
              Polygon
            </SubgraphLink>
          </p>
          <CodeSnippet>{agentTxCountsQuery}</CodeSnippet>
        </div>
      </SectionWrapper>
    </>
  );
};
