import { SUB_HEADER_LG_CLASS, TEXT_MEDIUM_CLASS } from 'common-util/classes';
import { registryGlobalsQuery } from 'common-util/graphql/queries';
import SectionWrapper from 'components/Layout/SectionWrapper';
import { ExternalLink } from 'components/ui/typography';
import { CodeSnippet } from './CodeSnippet';

export const TransactionsInfo = () => {
  return (
    <SectionWrapper id="transactions">
      <h2 className={SUB_HEADER_LG_CLASS}>Transactions</h2>

      <div className="space-y-6 mt-4">
        <p>
          Tracks the total number of transactions executed by all agents across
          all supported networks. This metric provides insight into the overall
          activity level and transaction volume generated by the autonomous
          agent ecosystem.
        </p>

        <p>The following query is used to compute total daily transactions:</p>

        <h3 className={`${TEXT_MEDIUM_CLASS} font-bold`}>
          Registry Globals query
        </h3>

        <p className="text-purple-600">
          Subgraph links:{' '}
          {[
            process.env.NEXT_PUBLIC_GNOSIS_REGISTRY_SUBGRAPH_URL,
            process.env.NEXT_PUBLIC_BASE_REGISTRY_SUBGRAPH_URL,
            process.env.NEXT_PUBLIC_MODE_REGISTRY_SUBGRAPH_URL,
            process.env.NEXT_PUBLIC_OPTIMISM_REGISTRY_SUBGRAPH_URL,
            process.env.NEXT_PUBLIC_CELO_REGISTRY_SUBGRAPH_URL,
            process.env.NEXT_PUBLIC_ETHEREUM_REGISTRY_SUBGRAPH_URL,
            process.env.NEXT_PUBLIC_ARBITRUM_REGISTRY_SUBGRAPH_URL,
            process.env.NEXT_PUBLIC_POLYGON_REGISTRY_SUBGRAPH_URL,
          ].map((link, index) => (
            <ExternalLink key={index} href={link} className="mr-2">
              {index + 1}
            </ExternalLink>
          ))}
        </p>
        <CodeSnippet>{registryGlobalsQuery}</CodeSnippet>
      </div>
    </SectionWrapper>
  );
};
